PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

CREATE TABLE IF NOT EXISTS [main].channel (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    vanity TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS [main].live (
    vid TEXT NOT NULL PRIMARY KEY,
    channel_id TEXT NOT NULL,
    live BOOLEAN NOT NULL DEFAULT 0 CHECK (live IN (0, 1)),
    title TEXT NOT NULL,
    thumbnail TEXT DEFAULT NULL,
    scheduled_start_time TIMESTAMP DEFAULT NULL,
    actual_start_time  TIMESTAMP DEFAULT NULL,
    view_count INTEGER DEFAULT 0,
    live_since TEXT DEFAULT NULL,
    start_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY(channel_id) REFERENCES channel(id)
);


CREATE TABLE IF NOT EXISTS [main].log_entry (
  id INTEGER NOT NULL PRIMARY KEY,
  error TEXT DEFAULT NULL,
  info TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL
);
